version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel:/var/www/html:ro
    networks:
      - laravel_net
    depends_on:
      - php
  mariadb:
    image: mariadb:11.3
    container_name: laravel_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
  # ports:
  #   - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel_net
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel_net
    depends_on:
      - mariadb
networks:
  laravel_net:
    driver: bridge
volumes:
  mariadb_data:
